import type { MaterialInbound, MaterialInventory, MaterialOutbound } from "@/types/materials";
import type { FinishedGoodsLot, ProductionResult, WorkOrder } from "@/types/production";
import type { CorrectiveAction, FinishedGoodsInspection, IncomingInspection, Nonconformity, ProcessInspection } from "@/types/quality";
import type { BackwardTraceData, ForwardTraceData, TraceConnection, TraceNode, TraceSearchResult } from "@/types/traceability";

export interface TraceabilityData {
  inventories: MaterialInventory[]; inbounds: MaterialInbound[]; outbounds: MaterialOutbound[];
  workOrders: WorkOrder[]; results: ProductionResult[]; fgLots: FinishedGoodsLot[];
  incoming: IncomingInspection[]; processList: ProcessInspection[]; finished: FinishedGoodsInspection[];
  nonconformities: Nonconformity[]; correctiveActions: CorrectiveAction[];
}

export function getIntegratedSearchResults(searchTerm:string,targetType="ALL",qualityStatus="ALL",data:Pick<TraceabilityData,"inventories"|"inbounds"|"fgLots">):TraceSearchResult[]{
  const query=searchTerm.trim().toLowerCase(); const results:TraceSearchResult[]=[];
  data.inventories.forEach(inv=>{const inbound=data.inbounds.find(x=>x.lotNo===inv.lotNo);if((!query||`${inv.lotNo} ${inv.materialCode} ${inv.materialName} ${inv.materialNameJa??""} ${inbound?.inboundNo??""}`.toLowerCase().includes(query))&&(targetType==="ALL"||targetType==="RAW_MATERIAL_LOT")&&(qualityStatus==="ALL"||inv.inspectionStatus===qualityStatus))results.push({id:`sr-raw-${inv.id}`,targetType:"RAW_MATERIAL_LOT",targetNo:inv.lotNo,targetName:inv.materialName,targetNameJa:inv.materialNameJa??inbound?.materialNameJa,lotNo:inv.lotNo,qualityStatus:inv.inspectionStatus,isTraceable:true,date:inbound?.inboundDate??""});});
  data.fgLots.forEach(lot=>{if((!query||`${lot.fgLotNo} ${lot.productCode} ${lot.productName} ${lot.productNameJa??""} ${lot.workOrderNo} ${lot.resultNo}`.toLowerCase().includes(query))&&(targetType==="ALL"||targetType==="FINISHED_GOODS_LOT")&&(qualityStatus==="ALL"||lot.qualityStatus===qualityStatus))results.push({id:`sr-fg-${lot.id}`,targetType:"FINISHED_GOODS_LOT",targetNo:lot.fgLotNo,targetName:lot.productName,targetNameJa:lot.productNameJa,lotNo:lot.fgLotNo,relatedWorkOrderNo:lot.workOrderNo,relatedResultNo:lot.resultNo,qualityStatus:lot.qualityStatus,isTraceable:true,date:lot.productionDate});}); return results;
}

export function getForwardTraceData(lotNo:string,data:TraceabilityData):ForwardTraceData|null{
  const inv=data.inventories.find(x=>x.lotNo===lotNo);const inbound=data.inbounds.find(x=>x.lotNo===lotNo);if(!inv&&!inbound)return null;
  const iqc=data.incoming.find(x=>x.lotNo===lotNo);const usage=data.outbounds.filter(x=>x.lotNo===lotNo).map(out=>{const wo=data.workOrders.find(x=>x.workOrderNo===out.workOrderNo);const result=data.results.find(x=>x.workOrderNo===out.workOrderNo);const fg=data.fgLots.find(x=>x.workOrderNo===out.workOrderNo);const fqc=data.finished.find(x=>x.fgLotNo===fg?.fgLotNo);const nc=data.nonconformities.find(x=>x.lotNo===fg?.fgLotNo||x.targetNo===out.workOrderNo);const ca=data.correctiveActions.find(x=>x.ncNo===nc?.ncNo);return{outboundNo:out.outboundNo,outboundDate:out.outboundDate,outboundQuantity:out.quantity,workOrderNo:out.workOrderNo,productionLine:out.productionLine,lineNameJa:out.productionLineJa??wo?.lineNameJa,productCode:wo?.productCode??"",productName:wo?.productName??"",productNameJa:wo?.productNameJa??fg?.productNameJa,workStatus:wo?.workStatus??"",resultNo:result?.resultNo,fgLotNo:fg?.fgLotNo,fgQualityStatus:fqc?.judgment??fg?.qualityStatus,fgIsReleaseAvailable:fg?.isReleaseAvailable,nonconformityNo:nc?.ncNo,correctiveActionNo:ca?.caNo};});
  return{rawMaterialLotNo:lotNo,materialCode:inv?.materialCode??inbound?.materialCode??"",materialName:inv?.materialName??inbound?.materialName??"",materialNameJa:inv?.materialNameJa??inbound?.materialNameJa,inboundNo:inbound?.inboundNo??"",inboundDate:inbound?.inboundDate??"",supplierName:inv?.supplierName??inbound?.supplierName??"",supplierNameJa:inv?.supplierNameJa??inbound?.supplierNameJa,inboundQuantity:inbound?.quantity??0,currentStock:inv?.currentStock??0,unit:inv?.unit??inbound?.unit??"",expirationDate:inv?.expirationDate??inbound?.expirationDate??"",inspectionStatus:inv?.inspectionStatus??inbound?.inspectionStatus??"PENDING",inventoryStatus:inv?.inventoryStatus??"NORMAL",iqcNo:iqc?.iqcNo,iqcJudgment:iqc?.judgment,usageList:usage,usedWorkOrdersCount:new Set(usage.map(x=>x.workOrderNo)).size,linkedResultsCount:usage.filter(x=>x.resultNo).length,generatedFGLotsCount:usage.filter(x=>x.fgLotNo).length,passedFGLotsCount:usage.filter(x=>x.fgQualityStatus==="PASSED").length,holdOrFailedFGLotsCount:usage.filter(x=>x.fgQualityStatus==="HOLD"||x.fgQualityStatus==="FAILED").length};
}
export const getForwardTraceByRawMaterialLot=getForwardTraceData;

export function getBackwardTraceData(fgLotNo:string,data:TraceabilityData):BackwardTraceData|null{
  const fg=data.fgLots.find(x=>x.fgLotNo===fgLotNo);if(!fg)return null;const wo=data.workOrders.find(x=>x.workOrderNo===fg.workOrderNo);const result=data.results.find(x=>x.resultNo===fg.resultNo);const fqc=data.finished.find(x=>x.fgLotNo===fgLotNo);const outs=data.outbounds.filter(x=>x.workOrderNo===fg.workOrderNo);const materials=outs.map(out=>{const inv=data.inventories.find(x=>x.lotNo===out.lotNo);const inbound=data.inbounds.find(x=>x.lotNo===out.lotNo);return{materialCode:out.materialCode,materialName:out.materialName,materialNameJa:out.materialNameJa??inv?.materialNameJa??inbound?.materialNameJa,rawMaterialLotNo:out.lotNo,outboundNo:out.outboundNo,usedQuantity:out.quantity,unit:out.unit,supplierName:inbound?.supplierName??inv?.supplierName??"",supplierNameJa:inbound?.supplierNameJa??inv?.supplierNameJa,inspectionStatus:inv?.inspectionStatus??"PENDING",manufactureDate:inbound?.manufactureDate??"",expirationDate:inv?.expirationDate??inbound?.expirationDate??""};});const lotNos=new Set(materials.map(x=>x.rawMaterialLotNo));const iqcs=data.incoming.filter(x=>lotNos.has(x.lotNo)).map(x=>({materialCode:x.materialCode,iqcNo:x.iqcNo,judgment:x.judgment}));const pqc=data.processList.find(x=>x.workOrderNo===fg.workOrderNo);const ncs=data.nonconformities.filter(x=>x.lotNo===fgLotNo||x.targetNo===fg.workOrderNo);const caNos=data.correctiveActions.filter(x=>ncs.some(n=>n.ncNo===x.ncNo)).map(x=>x.caNo);
  return{fgLotNo,productCode:fg.productCode,productName:fg.productName,productNameJa:fg.productNameJa??wo?.productNameJa,productionDate:fg.productionDate,productionLine:fg.productionLine,lineNameJa:fg.lineNameJa??wo?.lineNameJa,totalQuantity:fg.totalQuantity,goodQuantity:fg.goodQuantity,unit:fg.unit,expirationDate:fg.expirationDate,qualityStatus:fg.qualityStatus,isReleaseAvailable:fg.isReleaseAvailable,planNo:wo?.planNo??"",workOrderNo:fg.workOrderNo,resultNo:fg.resultNo,handler:result?.handler??wo?.handler??"",actualStartTime:result?.actualStartTime,actualEndTime:result?.actualEndTime,achievementRate:result?.achievementRate??0,defectRate:result?.defectRate??0,usedMaterials:materials,iqcResults:iqcs,pqcResult:pqc?{pqcNo:pqc.pqcNo,process:pqc.process,judgment:pqc.judgment}:undefined,fqcResult:fqc?{fqcNo:fqc.fqcNo,judgment:fqc.judgment}:undefined,nonconformityNos:ncs.map(x=>x.ncNo),correctiveActionNos:caNos,usedMaterialTypesCount:new Set(materials.map(x=>x.materialCode)).size,linkedRawLotCount:lotNos.size,completedInspectionsCount:iqcs.length+(pqc?1:0)+(fqc?1:0),nonconformityCount:ncs.length,unresolvedCACount:data.correctiveActions.filter(x=>caNos.includes(x.caNo)&&x.caStatus!=="CLOSED").length};
}
export const getBackwardTraceByFinishedGoodsLot=getBackwardTraceData;

export function getTraceRelationDiagramData(targetNo:string,data:TraceabilityData):{nodes:TraceNode[];connections:TraceConnection[]}{
  const backward=data.fgLots.some(x=>x.fgLotNo===targetNo);const fg=backward?data.fgLots.find(x=>x.fgLotNo===targetNo):data.fgLots.find(x=>data.outbounds.some(o=>o.lotNo===targetNo&&o.workOrderNo===x.workOrderNo));if(!fg)return{nodes:[],connections:[]};const wo=data.workOrders.find(x=>x.workOrderNo===fg.workOrderNo);const result=data.results.find(x=>x.resultNo===fg.resultNo);const outs=data.outbounds.filter(x=>x.workOrderNo===fg.workOrderNo);const nodes:TraceNode[]=[];const connections:TraceConnection[]=[];outs.forEach((out,index)=>{const id=`raw-${index}`;nodes.push({id,type:"RAW_MATERIAL_LOT",referenceNumber:out.lotNo,label:`${out.materialName} / ${out.quantity}${out.unit}`,status:(data.inventories.find(x=>x.lotNo===out.lotNo)?.inspectionStatus??"PENDING") as TraceNode["status"],occurredAt:out.outboundDate,relatedIds:["wo"]});connections.push({sourceId:id,targetId:"wo",relationType:`투입 ${out.quantity}${out.unit}`});});if(wo)nodes.push({id:"wo",type:"WORK_ORDER",referenceNumber:wo.workOrderNo,label:`${wo.productName} / ${wo.productionLine}`,status:wo.workStatus as TraceNode["status"],occurredAt:wo.plannedDate,handler:wo.handler,relatedIds:result?["result"]:["fg"]});if(result){nodes.push({id:"result",type:"PRODUCTION_RESULT",referenceNumber:result.resultNo,label:`생산 ${result.totalQuantity}${fg.unit} / 양품 ${result.goodQuantity}${fg.unit}`,status:result.resultStatus==="CONFIRMED"?"COMPLETED":"IN_PROGRESS",occurredAt:result.productionDate,handler:result.handler,relatedIds:["fg"]});connections.push({sourceId:"wo",targetId:"result",relationType:"실적 확정"});}nodes.push({id:"fg",type:"FINISHED_GOODS_LOT",referenceNumber:fg.fgLotNo,label:`${fg.productName} / ${fg.qualityStatus}`,status:fg.qualityStatus,occurredAt:fg.productionDate,relatedIds:[]});connections.push({sourceId:result?"result":"wo",targetId:"fg",relationType:"LOT 발행"});return{nodes,connections};
}
export const getTraceNodesAndConnections=getTraceRelationDiagramData;
