"use client";

import { FormEvent, useState } from "react";
import { useAdmin } from "@/context/AdminContext";
import type { CorrectiveAction, DepartmentCode, Nonconformity } from "@/types/quality";

export default function CorrectiveActionCreateModal({isOpen,onClose,nonconformities,onSubmit}:{isOpen:boolean;onClose:()=>void;nonconformities:Nonconformity[];onSubmit:(data:Omit<CorrectiveAction,"id"|"caNo"|"caStatus"|"verificationStatus">)=>boolean}){
  const {activeUsers}=useAdmin(); const [ncNo,setNcNo]=useState(""); const [requestDate,setRequestDate]=useState(new Date().toISOString().slice(0,10)); const [department,setDepartment]=useState<DepartmentCode>("QUALITY"); const [handler,setHandler]=useState(""); const [problemSummary,setProblemSummary]=useState(""); const [interimAction,setInterimAction]=useState(""); const [actionPlan,setActionPlan]=useState(""); const [preventiveMeasure,setPreventiveMeasure]=useState(""); const [dueDate,setDueDate]=useState("");
  if(!isOpen)return null; const submit=(e:FormEvent)=>{e.preventDefault();const ok=onSubmit({ncNo,requestDate,targetDepartment:department,handler,problemSummary,interimAction,actionPlan,preventiveMeasure,dueDate});if(ok)onClose();};
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-2xl rounded-xl bg-white shadow-xl"><div className="flex items-center justify-between border-b px-6 py-4"><h3 className="text-lg font-bold">시정조치 등록</h3><button onClick={onClose} className="text-2xl text-gray-400">×</button></div><form onSubmit={submit} className="space-y-4 p-6"><div className="grid gap-4 md:grid-cols-2"><Field label="연결 부적합 번호 *"><select required value={ncNo} onChange={e=>{setNcNo(e.target.value);const nc=nonconformities.find(x=>x.ncNo===e.target.value);if(nc)setProblemSummary(nc.details)}} className={input}><option value="">부적합 선택</option>{nonconformities.map(nc=><option key={nc.id} value={nc.ncNo}>{nc.ncNo} · {nc.targetName}</option>)}</select></Field><Field label="요청일 *"><input required type="date" value={requestDate} onChange={e=>setRequestDate(e.target.value)} className={input}/></Field><Field label="담당 부서 *"><select value={department} onChange={e=>setDepartment(e.target.value as DepartmentCode)} className={input}><option value="MATERIALS">자재</option><option value="PRODUCTION">생산</option><option value="QUALITY">품질</option><option value="FACILITY">설비</option><option value="HYGIENE">위생</option></select></Field><Field label="담당자 *"><input required list="ca-users" value={handler} onChange={e=>setHandler(e.target.value)} className={input}/><datalist id="ca-users">{activeUsers.map(user=><option key={user.id} value={user.name}/>)}</datalist></Field><Field label="완료 예정일 *"><input required type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} className={input}/></Field></div><Field label="불량 내용 / 문제 요약 *"><textarea required rows={3} value={problemSummary} onChange={e=>setProblemSummary(e.target.value)} className={input} placeholder="시정조치가 필요한 불량 내용을 입력하세요."/></Field><Field label="임시 조치"><textarea rows={2} value={interimAction} onChange={e=>setInterimAction(e.target.value)} className={input}/></Field><Field label="시정 조치 내용 *"><textarea required rows={3} value={actionPlan} onChange={e=>setActionPlan(e.target.value)} className={input} placeholder="실행할 시정 조치 내용을 입력하세요."/></Field><Field label="재발 방지 대책"><textarea rows={2} value={preventiveMeasure} onChange={e=>setPreventiveMeasure(e.target.value)} className={input}/></Field><div className="flex justify-end gap-2 border-t pt-4"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2">취소</button><button className="rounded-lg bg-amber-600 px-4 py-2 font-bold text-white">시정조치 등록</button></div></form></div></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1 block text-xs font-bold text-gray-700">{label}</span>{children}</label>}
const input="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none focus:border-amber-500";
