import { supabase } from "@/lib/supabase/client";
import type { CorrectiveAction, DefectHistory, FinishedGoodsInspection, IncomingInspection, InspectionCategory, InspectionItemResult, InspectionQueueItem, InspectionStatusHistoryItem, Nonconformity, ProcessInspection } from "@/types/quality";

export interface QualitySnapshot {
  queue: InspectionQueueItem[];
  incoming: IncomingInspection[];
  processList: ProcessInspection[];
  finished: FinishedGoodsInspection[];
  nonconformities: Nonconformity[];
  correctiveActions: CorrectiveAction[];
  defectHistory: DefectHistory[];
}

function check(error: { message: string } | null) { if (error) throw new Error(error.message); }
async function findId(table: "business_users" | "material_inbounds" | "work_orders" | "finished_goods_lots" | "products" | "nonconformities", column: string, value: string) {
  if (!value) return null;
  const result = await supabase.from(table).select("id").eq(column, value).maybeSingle();
  check(result.error); return result.data?.id ?? null;
}
const dateTime = (value: string) => value ? value.replace("T", " ").slice(0, 16) : "";

export async function fetchQualitySnapshot(): Promise<QualitySnapshot> {
  const requests = [
    supabase.from("inspection_requests").select("*").order("request_time", { ascending: false }),
    supabase.from("incoming_inspections").select("*").order("inspection_date", { ascending: false }),
    supabase.from("process_inspections").select("*").order("inspection_date", { ascending: false }),
    supabase.from("finished_goods_inspections").select("*").order("inspection_date", { ascending: false }),
    supabase.from("inspection_item_results").select("*"),
    supabase.from("inspection_status_history").select("*").order("changed_at"),
    supabase.from("material_inbounds").select("*"), supabase.from("materials").select("id,code,name"),
    supabase.from("suppliers").select("id,name"), supabase.from("work_orders").select("*"),
    supabase.from("products").select("id,code,name"), supabase.from("production_lines").select("id,name"),
    supabase.from("finished_goods_lots").select("*"), supabase.from("production_results").select("id,result_no"),
    supabase.from("defect_histories").select("*").order("inspection_date", { ascending: false }),
    supabase.from("nonconformities").select("*").order("occurred_date", { ascending: false }),
    supabase.from("corrective_actions").select("*").order("request_date", { ascending: false }),
  ] as const;
  const [queueR, incomingR, processR, finishedR, itemsR, historyR, inboundsR, materialsR, suppliersR, workOrdersR, productsR, linesR, lotsR, resultsR, defectsR, ncR, caR] = await Promise.all(requests);
  for (const result of [queueR,incomingR,processR,finishedR,itemsR,historyR,inboundsR,materialsR,suppliersR,workOrdersR,productsR,linesR,lotsR,resultsR,defectsR,ncR,caR]) check(result.error);
  const byId = <T extends { id: string }>(rows: T[] | null) => new Map((rows ?? []).map(row => [row.id, row]));
  const inbounds = byId(inboundsR.data), materials = byId(materialsR.data), suppliers = byId(suppliersR.data);
  const workOrders = byId(workOrdersR.data), products = byId(productsR.data), lines = byId(linesR.data);
  const lots = byId(lotsR.data), results = byId(resultsR.data), nonconformityById = byId(ncR.data);
  const itemMap = new Map<string, InspectionItemResult[]>(), historyMap = new Map<string, InspectionStatusHistoryItem[]>();
  const owner = (row: Record<string, unknown>) => String(row.incoming_inspection_id ?? row.process_inspection_id ?? row.finished_goods_inspection_id ?? "");
  for (const row of itemsR.data ?? []) { const key=owner(row); const list=itemMap.get(key)??[]; list.push({itemName:row.item_name,standardValue:row.standard_value,measuredValue:row.measured_value,unit:row.unit??undefined,isMandatory:row.is_mandatory,result:row.result,notes:row.notes??undefined}); itemMap.set(key,list); }
  for (const row of historyR.data ?? []) { const key=owner(row); const list=historyMap.get(key)??[]; list.push({id:row.id,changeTime:dateTime(row.changed_at),previousStatus:row.previous_status,newStatus:row.new_status,changedBy:row.changed_by_name,reason:row.reason??undefined}); historyMap.set(key,list); }
  return {
    queue:(queueR.data??[]).map(r=>({id:r.id,requestNo:r.request_no,requestTime:dateTime(r.request_time),category:r.category,targetNo:r.target_no,targetName:r.target_name,lotNo:r.lot_no,lineOrSupplier:r.line_or_supplier,requester:r.requester_name,inspector:r.inspector_name??undefined,priority:r.priority,status:r.status,notes:r.notes??undefined})),
    incoming:(incomingR.data??[]).map(r=>{const ib=inbounds.get(r.inbound_id); const mat=ib?materials.get(ib.material_id):undefined; return {id:r.id,iqcNo:r.iqc_no,inboundNo:ib?.inbound_no??"",inboundDate:ib?.inbound_date??"",materialCode:mat?.code??"",materialName:mat?.name??"",lotNo:ib?.lot_no??"",supplierName:(ib?.supplier_id?suppliers.get(ib.supplier_id)?.name:"")??"",quantity:Number(ib?.quantity??0),unit:ib?.unit??"",manufactureDate:ib?.manufacture_date??"",expirationDate:ib?.expiration_date??"",inspector:r.inspector_name,inspectionDate:dateTime(r.inspection_date),status:r.status,judgment:r.judgment,judgmentReason:r.judgment_reason??undefined,items:itemMap.get(r.id)??[],attachmentFileName:r.attachment_file_name??undefined,previousInspectionNo:r.previous_inspection_id??undefined,statusHistory:historyMap.get(r.id)??[]};}),
    processList:(processR.data??[]).map(r=>{const wo=workOrders.get(r.work_order_id); const product=wo?products.get(wo.product_id):undefined; return {id:r.id,pqcNo:r.pqc_no,workOrderNo:wo?.work_order_no??"",productionDate:r.production_date,productCode:product?.code??"",productName:product?.name??"",productionLine:(wo?.production_line_id?lines.get(wo.production_line_id)?.name:"")??"",process:r.process,inspectionTiming:r.inspection_timing,worker:r.worker_name,inspector:r.inspector_name,inspectionDate:dateTime(r.inspection_date),status:r.status,judgment:r.judgment,judgmentReason:r.judgment_reason??undefined,followUpAction:r.follow_up_action??undefined,items:itemMap.get(r.id)??[],previousInspectionNo:r.previous_inspection_id??undefined,statusHistory:historyMap.get(r.id)??[]};}),
    finished:(finishedR.data??[]).map(r=>{const lot=lots.get(r.finished_goods_lot_id); const product=lot?products.get(lot.product_id):undefined; const wo=lot?workOrders.get(lot.work_order_id):undefined; return {id:r.id,fqcNo:r.fqc_no,fgLotNo:lot?.fg_lot_no??"",resultNo:(lot?.production_result_id?results.get(lot.production_result_id)?.result_no:"")??"",workOrderNo:wo?.work_order_no??"",productionDate:lot?.production_date??"",productCode:product?.code??"",productName:product?.name??"",productionLine:(lot?.production_line_id?lines.get(lot.production_line_id)?.name:"")??"",totalQuantity:Number(lot?.total_quantity??0),unit:lot?.unit??"",sampleQuantity:Number(r.sample_quantity),defectiveSampleQuantity:Number(r.defective_sample_quantity),avgWeight:Number(r.avg_weight),minWeight:Number(r.min_weight),maxWeight:Number(r.max_weight),inspector:r.inspector_name,inspectionDate:dateTime(r.inspection_date),status:r.status,judgment:r.judgment,judgmentReason:r.judgment_reason??undefined,isReleaseAvailable:r.is_release_available,recheckRequired:r.recheck_required,items:itemMap.get(r.id)??[],previousInspectionNo:r.previous_inspection_id??undefined,statusHistory:historyMap.get(r.id)??[]};}),
    defectHistory:(defectsR.data??[]).map(r=>({id:r.id,defectNo:r.defect_no,lotNumber:lots.get(r.finished_goods_lot_id)?.fg_lot_no??"",productId:products.get(r.product_id)?.code??r.product_id,productName:products.get(r.product_id)?.name??"",productionDate:r.production_date,inspectionDate:dateTime(r.inspection_date),inspector:r.inspector_name,defectType:r.defect_type,defectQuantity:Number(r.defect_quantity),defectRate:Number(r.defect_rate),cause:r.cause,correctiveAction:r.corrective_action,status:r.status,assignee:r.assignee_name,createdAt:dateTime(r.created_at),updatedAt:dateTime(r.updated_at)})),
    nonconformities:(ncR.data??[]).map(r=>({id:r.id,ncNo:r.nc_no,occurredDate:r.occurred_date,category:r.category,inspectionNo:r.inspection_no,targetNo:r.target_no,targetName:r.target_name,lotNo:r.lot_no,ncType:r.nc_type,defectQuantity:Number(r.defect_quantity),unit:r.unit,severity:r.severity,ncStatus:r.nc_status,handler:r.handler_name,dueDate:r.due_date,details:r.details,interimAction:r.interim_action??undefined,adminMemo:r.admin_memo??undefined,correctiveActionNo:(caR.data??[]).find(c=>c.nonconformity_id===r.id)?.ca_no})),
    correctiveActions:(caR.data??[]).map(r=>({id:r.id,caNo:r.ca_no,ncNo:nonconformityById.get(r.nonconformity_id)?.nc_no??"",requestDate:r.request_date,targetDepartment:r.target_department,handler:r.handler_name,problemSummary:r.problem_summary,interimAction:r.interim_action??undefined,directCause:r.direct_cause??undefined,rootCause:r.root_cause??undefined,analysisMethod:r.analysis_method??undefined,actionPlan:r.action_plan??undefined,preventiveMeasure:r.preventive_measure??undefined,caStatus:r.ca_status,startDate:r.start_date??undefined,dueDate:r.due_date,completedDate:r.completed_date??undefined,verificationContent:r.verification_content??undefined,verifier:r.verifier_name??undefined,verificationDate:r.verification_date??undefined,verificationStatus:r.verification_status})),
  };
}

export async function saveInspectionRequest(item: InspectionQueueItem) { const inspectorId=await findId("business_users","name",item.inspector??""); const requesterId=await findId("business_users","name",item.requester); const {error}=await supabase.from("inspection_requests").upsert({id:item.id,request_no:item.requestNo,request_time:item.requestTime,category:item.category,target_no:item.targetNo,target_name:item.targetName,lot_no:item.lotNo,line_or_supplier:item.lineOrSupplier,requester_user_id:requesterId,requester_name:item.requester,inspector_user_id:inspectorId,inspector_name:item.inspector??null,priority:item.priority,status:item.status,notes:item.notes??null},{onConflict:"id"}); check(error); }

async function saveChildren(id:string, category:InspectionCategory, items:InspectionItemResult[], history:InspectionStatusHistoryItem[]) { const fk=category==="INCOMING"?"incoming_inspection_id":category==="PROCESS"?"process_inspection_id":"finished_goods_inspection_id"; if(items.length){const {error}=await supabase.from("inspection_item_results").insert(items.map(x=>({inspection_category:category,[fk]:id,item_name:x.itemName,standard_value:x.standardValue,measured_value:x.measuredValue,unit:x.unit??null,is_mandatory:x.isMandatory,result:x.result,notes:x.notes??null})));check(error);} for(const h of history){const changedBy=await findId("business_users","name",h.changedBy);const {error}=await supabase.from("inspection_status_history").upsert({id:`${id}-${h.id}`,inspection_category:category,[fk]:id,changed_at:h.changeTime,previous_status:h.previousStatus,new_status:h.newStatus,changed_by_user_id:changedBy,changed_by_name:h.changedBy,reason:h.reason??null},{onConflict:"id"});check(error);} }
export async function saveIncomingInspection(x:IncomingInspection){const inboundId=await findId("material_inbounds","inbound_no",x.inboundNo);const inspectorId=await findId("business_users","name",x.inspector);if(!inboundId)throw new Error("입고 ID를 찾을 수 없습니다.");const {error}=await supabase.from("incoming_inspections").upsert({id:x.id,iqc_no:x.iqcNo,inbound_id:inboundId,inspector_user_id:inspectorId,inspector_name:x.inspector,inspection_date:x.inspectionDate,status:x.status,judgment:x.judgment,judgment_reason:x.judgmentReason??null,attachment_file_name:x.attachmentFileName??null},{onConflict:"id"});check(error);await saveChildren(x.id,"INCOMING",x.items,x.statusHistory);}
export async function saveProcessInspection(x:ProcessInspection){const workOrderId=await findId("work_orders","work_order_no",x.workOrderNo);const inspectorId=await findId("business_users","name",x.inspector);const workerId=await findId("business_users","name",x.worker);if(!workOrderId)throw new Error("작업지시 ID를 찾을 수 없습니다.");const {error}=await supabase.from("process_inspections").upsert({id:x.id,pqc_no:x.pqcNo,work_order_id:workOrderId,production_date:x.productionDate,process:x.process,inspection_timing:x.inspectionTiming,worker_user_id:workerId,worker_name:x.worker,inspector_user_id:inspectorId,inspector_name:x.inspector,inspection_date:x.inspectionDate,status:x.status,judgment:x.judgment,judgment_reason:x.judgmentReason??null,follow_up_action:x.followUpAction??null},{onConflict:"id"});check(error);await saveChildren(x.id,"PROCESS",x.items,x.statusHistory);}
export async function saveFinishedInspection(x:FinishedGoodsInspection){const lotId=await findId("finished_goods_lots","fg_lot_no",x.fgLotNo);const inspectorId=await findId("business_users","name",x.inspector);if(!lotId)throw new Error("완제품 LOT ID를 찾을 수 없습니다.");const {error}=await supabase.from("finished_goods_inspections").upsert({id:x.id,fqc_no:x.fqcNo,finished_goods_lot_id:lotId,sample_quantity:x.sampleQuantity,defective_sample_quantity:x.defectiveSampleQuantity,avg_weight:x.avgWeight,min_weight:x.minWeight,max_weight:x.maxWeight,inspector_user_id:inspectorId,inspector_name:x.inspector,inspection_date:x.inspectionDate,status:x.status,judgment:x.judgment,judgment_reason:x.judgmentReason??null,is_release_available:x.isReleaseAvailable,recheck_required:x.recheckRequired},{onConflict:"id"});check(error);await saveChildren(x.id,"FINISHED_GOODS",x.items,x.statusHistory);}
export async function saveDefectHistory(x:DefectHistory){const lotId=await findId("finished_goods_lots","fg_lot_no",x.lotNumber);const productId=await findId("products","code",x.productId);const inspectorId=await findId("business_users","name",x.inspector);const assigneeId=await findId("business_users","name",x.assignee);if(!lotId||!productId)throw new Error("불량 이력 관계 ID를 찾을 수 없습니다.");const {error}=await supabase.from("defect_histories").upsert({id:x.id,defect_no:x.defectNo,finished_goods_lot_id:lotId,product_id:productId,production_date:x.productionDate,inspection_date:x.inspectionDate,inspector_user_id:inspectorId,inspector_name:x.inspector,defect_type:x.defectType,defect_quantity:x.defectQuantity,defect_rate:x.defectRate,cause:x.cause,corrective_action:x.correctiveAction,status:x.status,assignee_user_id:assigneeId,assignee_name:x.assignee},{onConflict:"id"});check(error);}
export async function saveNonconformity(x:Nonconformity){const handlerId=await findId("business_users","name",x.handler);const {error}=await supabase.from("nonconformities").upsert({id:x.id,nc_no:x.ncNo,occurred_date:x.occurredDate,category:x.category,inspection_no:x.inspectionNo,target_no:x.targetNo,target_name:x.targetName,lot_no:x.lotNo,nc_type:x.ncType,defect_quantity:x.defectQuantity,unit:x.unit,severity:x.severity,nc_status:x.ncStatus,handler_user_id:handlerId,handler_name:x.handler,due_date:x.dueDate,details:x.details,interim_action:x.interimAction??null,admin_memo:x.adminMemo??null},{onConflict:"id"});check(error);}
export async function saveCorrectiveAction(x:CorrectiveAction){const ncId=await findId("nonconformities","nc_no",x.ncNo);const handlerId=await findId("business_users","name",x.handler);const verifierId=await findId("business_users","name",x.verifier??"");if(!ncId)throw new Error("부적합 ID를 찾을 수 없습니다.");const {error}=await supabase.from("corrective_actions").upsert({id:x.id,ca_no:x.caNo,nonconformity_id:ncId,request_date:x.requestDate,target_department:x.targetDepartment,handler_user_id:handlerId,handler_name:x.handler,problem_summary:x.problemSummary,interim_action:x.interimAction??null,direct_cause:x.directCause??null,root_cause:x.rootCause??null,analysis_method:x.analysisMethod??null,action_plan:x.actionPlan??null,preventive_measure:x.preventiveMeasure??null,ca_status:x.caStatus,start_date:x.startDate??null,due_date:x.dueDate,completed_date:x.completedDate??null,verification_content:x.verificationContent??null,verifier_user_id:verifierId,verifier_name:x.verifier??null,verification_date:x.verificationDate??null,verification_status:x.verificationStatus},{onConflict:"id"});check(error);}
